version: '2'
services:
 shobdo:
  image: "stupefied/shobdo:latest"
  ports:
  - "9000:9000"
  depends_on:
  - "redis"
  - "mongo"
 redis:
  image: "redis:latest"
 mongo:
  image: "mongo:latest"
  volumes:
  - "../../data/mongodump:/mongoshobdodump"

