version: '2'
services:
 mongo:
  image: "mongo:latest"
  volumes:
  - "./data/mongodump:/mongoshobdodump"
 redis:
  image: "redis:latest"
  depends_on:
  - "mongo"
 shobdo:
  image: "dict-app"
  environment:
  - "SHOBDO_MONGODBHOSTNAME=mongo"
  - "SHOBDO_REDISHOSTNAME=redis"
  depends_on:
  - "redis"
  - "mongo"
 client:
  image: "nginx"
  ports:
  - "32779:80"
  depends_on:
  - "shobdo"
  volumes:
  - "./client/html/public/:/usr/share/nginx/html/"
  - "./client/nginx.conf:/etc/nginx/nginx.conf"

